config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5:
      branch: main
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5 git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-seashell-chinook.sh
        container: qc.acc_flaky-salmon-devil
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-pink-octopus.sh
        container: qc.doc_snippy-auburn-grouse
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5 git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-linen-uakari.sh
        container: qc.doc_fuzzy-sepia-cheetah
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-ruby-discus.sh
        container: qc.doc_whiny-plum-butterfly
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-harlequin-bandicoot.sh
        container: qc.lic_silly-azure-chow
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-harlequin-catfish.sh
        container: qc.sec_gloppy-sepia-saola
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ultramarine-lemur.sh
        container: qc.sty_hasty-mauve-horse
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5 jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cobalt-booby.sh
        container: qc.sty_pasty-dandelion-dane
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-maroon-bobcat.sh
        container: qc.uni_gummy-ultramarine-fousek
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-era5 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-cerise-gharial.sh
        container: qc.ver_gloppy-turquoise-mongoose
timeout: 5400
